# Generated by Django 3.2.8 on 2021-10-23 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=512, null=True, verbose_name='Word')),
                ('language', models.CharField(choices=[('EN', '🇬🇧 English'), ('RU', '🇷🇺 Russian')], default='EN', max_length=2, null=True, verbose_name='Language')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('translations', models.ManyToManyField(related_name='_dictionary_wordtranslation_translations_+', to='dictionary.WordTranslation', verbose_name='Translations')),
            ],
            options={
                'verbose_name': 'Word translation',
                'verbose_name_plural': 'Word translations',
                'ordering': ('-modified',),
                'unique_together': {('word', 'description')},
            },
        ),
    ]
