# Generated by Django 3.2.8 on 2021-10-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtranslation',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_dictionary_wordtranslation_translations_+', to='dictionary.WordTranslation', verbose_name='Translations'),
        ),
    ]
