# Generated by Django 3.2.8 on 2021-10-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_wordtranslation_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtranslation',
            name='language_from',
            field=models.CharField(choices=[('EN', '🇬🇧 English'), ('RU', '🇷🇺 Russian')], default='EN', max_length=2, null=True, verbose_name='Language (From)'),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='language_to',
            field=models.CharField(choices=[('EN', '🇬🇧 English'), ('RU', '🇷🇺 Russian')], default='RU', max_length=2, null=True, verbose_name='Language (To)'),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='word_from',
            field=models.CharField(max_length=512, null=True, verbose_name='Word (From)'),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='word_to',
            field=models.CharField(max_length=512, null=True, verbose_name='Word (To)'),
        ),
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('word_from', 'word_to')},
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='word',
        ),
    ]
