# Generated by Django 3.2.8 on 2021-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20211028_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtranslation',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source'),
        ),
    ]
